### ISSUE TITLE
Problem with ) char

### ISSUE THREAD

**Issue by spayton** [MrcSnm/define_macro-loader#2]
I'm still using this immensly useful tool, helps me use JS the way I want to.

It does have a problem with the ')' char, both with a passed string parameter and also when present in an end of line comment.  Here's an example of both using this test DEFINE.

```
DEFINE(_TEST, (a) =>
{
console.log(a);
});
```

eg 1.

`_TEST("function()");  // compiles ok but output is "function("`

eg 2.

```
_TEST("function()");  // doesn't like ) in end of line comment, compile error

Module parse failed: Unexpected token (633:1)
File was processed with these loaders:
 * ./src/libs/define_macro-loader.old.js
You may need an additional loader to handle the result of these loaders.
|
|     console.log("function()");

```

**Comment by MrcSnm** [comment]
Fixed

**Comment by spayton** [comment]
Thanks, that fixes the 1st problem, the main problem I kept hitting.  The other problem is still there, although that's lot easier to avoid.  The problem is that it doesn't like the ')' char appearing in the comment block, either of these breaks the build.

```
_TEST("function()");  /* output should be "function()" */
_TEST("function()");  // output should be "function()"

```

**Comment by MrcSnm** [comment]
Trying to implement that fix, it seems it is harder than it appears, will return to do that once I have free time
